# Chicago Staging Site

apiVersion: siteops/v1
kind: Site
name: chicago-staging
inherits: shared/usa-east.yaml

# subscription, location, country inherited from shared/usa-east.yaml
resourceGroup: rg-iot-chicago-staging

labels:
  environment: staging
  city: Chicago

properties:
  deployOptions:
    includeSolution: false
    includeOpcPlcSimulator: false

parameters:
  clusterName: chicago-staging-arc
