# Chicago Staging Site

apiVersion: siteops/v1
kind: Site
name: chicago-staging
inherits: base-site.yaml

subscription: "00000000-0000-0000-0000-000000000000"
resourceGroup: rg-iot-chicago-staging
location: eastus

labels:
  environment: staging
  country: US
  city: Chicago

properties:
  deployOptions:
    includeSolution: false
    includeOpcPlcSimulator: false

parameters:
  clusterName: chicago-staging-arc
