<#
.SYNOPSIS
Generates `Install-AksEeBootstrap.ps1` by embedding `worker.ps1` and
`aksedge-config.template.json` into `launcher-template.ps1` at the
`__EMBEDDED_WORKER_PS1__` and `__EMBEDDED_AKSEDGE_TEMPLATE__` sentinels.

.DESCRIPTION
Run this after editing any of `worker.ps1`,
`aksedge-config.template.json`, or `launcher-template.ps1`. Output is a
self-contained launcher that the operator runs directly on a VM or that
scalekit delivers via Arc run-command.

.PARAMETER ScriptDir
Directory containing the three source files. Defaults to the directory
containing this script.

.EXAMPLE
    .\Build-Launcher.ps1
    Reads sources from this directory and writes Install-AksEeBootstrap.ps1
    alongside.
#>

[CmdletBinding()]
param(
    [string]$ScriptDir = $PSScriptRoot
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$templatePath  = Join-Path $ScriptDir 'launcher-template.ps1'
$workerPath    = Join-Path $ScriptDir 'worker.ps1'
$aksEdgePath   = Join-Path $ScriptDir 'aksedge-config.template.json'
$outputPath    = Join-Path $ScriptDir 'Install-AksEeBootstrap.ps1'

foreach ($p in @($templatePath, $workerPath, $aksEdgePath)) {
    if (-not (Test-Path $p)) { throw "Missing source: $p" }
}

$template    = Get-Content -Raw -Path $templatePath
$worker      = Get-Content -Raw -Path $workerPath
$aksTemplate = Get-Content -Raw -Path $aksEdgePath

# Defensive: a closing here-string terminator inside the embedded content
# would break the generated launcher. Both worker.ps1 and the AKS EE JSON
# template are unlikely to contain `'@` at column zero, but check anyway.
foreach ($pair in @(@{Name='worker.ps1'; Content=$worker}, @{Name='aksedge-config.template.json'; Content=$aksTemplate})) {
    $hasTerminator = [regex]::IsMatch($pair.Content, '(?m)^''@')
    if ($hasTerminator) {
        throw "$($pair.Name) contains a literal `'@` at column 0, which would terminate the embedded here-string. Re-author to avoid that pattern."
    }
}

# Trim a single trailing newline if present so the embedded content does
# not introduce an extra blank line before the closing `'@`.
$worker      = $worker.TrimEnd("`r", "`n")
$aksTemplate = $aksTemplate.TrimEnd("`r", "`n")

# Use a MatchEvaluator so $-substitutions in the source content are not
# interpreted as regex back-references during replacement.
$rendered = [regex]::Replace(
    $template,
    '__EMBEDDED_WORKER_PS1__',
    { param($match) return $worker })
$rendered = [regex]::Replace(
    $rendered,
    '__EMBEDDED_AKSEDGE_TEMPLATE__',
    { param($match) return $aksTemplate })

# Prepend a do-not-edit banner so a casual reader knows the file is
# generated. Sits above the help block so it shows up first in any editor.
$banner = @"
# ============================================================================
# DO NOT EDIT THIS FILE.
# Generated by Build-Launcher.ps1 from:
#   - launcher-template.ps1
#   - worker.ps1
#   - aksedge-config.template.json
# Edit those sources and re-run Build-Launcher.ps1 to regenerate.
# ============================================================================

"@
$rendered = $banner + $rendered

Set-Content -Path $outputPath -Value $rendered -Encoding UTF8

$tokens = $null; $errors = $null
[System.Management.Automation.Language.Parser]::ParseFile($outputPath, [ref]$tokens, [ref]$errors) | Out-Null
if ($errors.Count -gt 0) {
    Write-Error "Generated launcher has parse errors:"
    $errors | ForEach-Object { Write-Error "  $($_.Extent.StartLineNumber):$($_.Extent.StartColumnNumber)  $($_.Message)" }
    throw 'Parse check failed. Inspect Install-AksEeBootstrap.ps1.'
}

$lines = (Get-Content -Path $outputPath).Count
Write-Host "Generated $outputPath ($lines lines, parse OK)"

# Also emit a minified variant for Arc Run Command delivery. The
# Microsoft.HybridCompute runCommands API enforces a size limit on the
# `script` body. The official Microsoft docs do NOT specify a number,
# but empirically (this workstream, 2026-06-08) the boundary sits
# around 38 KB raw: 37.6 KB worked, 38.8 KB returned HCRP413. After
# JSON encoding (each `\` -> `\\`, each `"` -> `\"`, each newline ->
# `\r\n`) plus ARM envelope overhead the request body grows further,
# which is what the RP is actually limiting. Stripping comments +
# blank lines + leading whitespace cuts the full ~53 KB source to
# ~34 KB. The full launcher remains for operator-direct use.
#
# Long-term scalability fix: switch to `scriptUri` (SAS URL to a
# blob) on the runCommands resource. scriptUri has no documented
# size limit but adds a storage account dependency to the deploy
# chain. Tracked separately.
#
# Minify each source file independently before substituting. The
# previous "minify after rendering" approach ran a comment-strip regex
# over here-string bodies, which silently corrupted any embedded content
# whose line started with `#`. Per-file minification keeps the regex
# scoped to one source at a time. The assertion below additionally
# refuses to minify if a future edit adds a here-string to worker.ps1,
# since that case would re-introduce the same corruption risk.
$minPath = Join-Path $ScriptDir 'Install-AksEeBootstrap.min.ps1'

function script:Compact-PSSource {
    param([string]$Source)
    $s = [regex]::Replace($Source, '(?s)<#.*?#>', '')
    $kept = New-Object System.Collections.Generic.List[string]
    foreach ($line in ($s -split "`r?`n")) {
        if ($line -match '^\s*#') { continue }
        if ($line -match '^\s*$') { continue }
        $kept.Add($line.Trim())
    }
    return ($kept -join "`r`n")
}

if ($worker -match "(?m)^@['""]") {
    throw "worker.ps1 contains a here-string opener. The per-file minifier strips leading whitespace and can silently corrupt here-string bodies. Either remove the here-string from worker.ps1 or upgrade Compact-PSSource to skip string tokens via [System.Management.Automation.PSParser]::Tokenize."
}

$minLauncherWrapper = script:Compact-PSSource $template
$minWorker          = script:Compact-PSSource $worker
$minAksTemplate     = ($aksTemplate | ConvertFrom-Json | ConvertTo-Json -Depth 20 -Compress)

$minified = [regex]::Replace(
    $minLauncherWrapper,
    '__EMBEDDED_WORKER_PS1__',
    { param($match) return $minWorker })
$minified = [regex]::Replace(
    $minified,
    '__EMBEDDED_AKSEDGE_TEMPLATE__',
    { param($match) return $minAksTemplate })

$minBanner = "# Generated minified launcher. Edit Build-Launcher.ps1 sources, not this file."
$minContent = $minBanner + "`r`n" + $minified

Set-Content -Path $minPath -Value $minContent -Encoding UTF8

$minTokens = $null; $minErrors = $null
[System.Management.Automation.Language.Parser]::ParseFile($minPath, [ref]$minTokens, [ref]$minErrors) | Out-Null
if ($minErrors.Count -gt 0) {
    Write-Error "Minified launcher has parse errors:"
    $minErrors | ForEach-Object { Write-Error "  $($_.Extent.StartLineNumber):$($_.Extent.StartColumnNumber)  $($_.Message)" }
    throw 'Minified parse check failed. Inspect Install-AksEeBootstrap.min.ps1.'
}

$minBytes = (Get-Item $minPath).Length
$minLines = (Get-Content $minPath).Count
Write-Host ("Generated {0} ({1} lines, {2:N0} bytes, parse OK)" -f $minPath, $minLines, $minBytes)
if ($minBytes -gt 36000) {
    Write-Warning ("Minified launcher is {0:N0} bytes. Empirical HCRP413 boundary for Microsoft.HybridCompute runCommands sits around 38 KB raw on 2026-06-08. Slim the source or move to scriptUri delivery before this grows further." -f $minBytes)
}
