# ============================================================================
# DO NOT EDIT THIS FILE.
# Generated by Build-Launcher.ps1 from:
#   - launcher-template.ps1
#   - worker.ps1
#   - aksedge-config.template.json
# Edit those sources and re-run Build-Launcher.ps1 to regenerate.
# ============================================================================
<#
.SYNOPSIS
Launcher for the AKS Edge Essentials + AIO bootstrap. Writes the worker
state-machine to disk, registers a Scheduled Task that drives it through
all phases (including the Hyper-V reboot), and returns once the task is
registered. Intended for either direct invocation on a Windows VM or
delivery via Azure Arc run-command.

.DESCRIPTION
The launcher is self-contained. It embeds `worker.ps1` and the AKS EE
config template as here-strings, so the entire bootstrap can be delivered
as a single `Microsoft.HybridCompute/machines/runCommands` script body.

Steps:
  1. Verify admin privileges and tighten ACLs on the config directory.
  2. Write the embedded worker and template to the config directory.
  3. Create (or refresh) a dedicated local admin user for the Scheduled
     Task. The password is generated on-box and never transmitted.
  4. Encrypt the caller-supplied service principal password via DPAPI
     (LocalMachine scope) so it does not sit in plaintext on disk.
  5. Write `config.json` and the initial `state.json` (phase=0).
  6. Register a Scheduled Task with at-startup + immediate triggers that
     runs `worker.ps1` as the local admin user.
  7. Start the task and return `REGISTERED` so the caller sees success.

The Scheduled Task survives reboots (at-startup trigger) so Phase 1's
Hyper-V enablement does not lose state.

.PARAMETER ClusterName
Name of the Arc-connected Kubernetes cluster that AKS EE will register.
Must match the `clusterName` the scalekit site overlay expects.

.PARAMETER ResourceGroup
Resource group that holds the Arc-connected server resource and will
receive the new connectedClusters resource.

.PARAMETER Subscription
Subscription ID.

.PARAMETER Location
Azure region for the connectedClusters and custom-location resources.

.PARAMETER TenantId
Azure AD tenant ID for the service principal.

.PARAMETER CustomLocationsOid
Tenant-wide object ID for the Custom Locations RP service principal.

.PARAMETER SpAppId
Service principal application ID. AKS Edge Essentials requires SP credentials
to create the cluster (Phase 2), so this is part of the standard happy path.
Leave empty only when running the bootstrap against an already-existing
cluster (Phase 2 short-circuits via deployment detection, and Phase 3 falls
through to the machine's managed identity). Must be paired with SpPassword.

.PARAMETER SpPassword
Service principal client secret. Required when SpAppId is set. Encrypted
at rest before the worker reads it back. The launcher reads this once and
discards the plaintext after encryption.

.PARAMETER AksEdgeMsiUrl
URL of the AKS Edge Essentials MSI to install. Pin a known-good version.

.PARAMETER ConfigDir
Directory holding all worker artifacts. Defaults to
`C:\ProgramData\siteops\aksee-bootstrap`. Override for local testing.

.PARAMETER ScheduledTaskName
Name of the Scheduled Task. Defaults to `SiteOpsAksEeBootstrap`. Set
explicitly only if multiple bootstraps run on the same host.

.PARAMETER LocalAdminUser
Local user the Scheduled Task runs as. Defaults to `siteops-bootstrap`.
The launcher creates the user (or resets its password) and adds it to
the local Administrators group.

.EXAMPLE
    # Standard happy path. SP creates the cluster (Phase 2); Phase 3
    # operations use the Arc machine's managed identity by default.
    .\Install-AksEeBootstrap.ps1 `
        -ClusterName        aksee-cluster1 `
        -ResourceGroup      aksee-rg `
        -Subscription       00000000-0000-0000-0000-000000000000 `
        -Location           westus3 `
        -TenantId           00000000-0000-0000-0000-000000000000 `
        -CustomLocationsOid 00000000-0000-0000-0000-000000000000 `
        -SpAppId            00000000-0000-0000-0000-000000000000 `
        -SpPassword         <secret> `
        -AksEdgeMsiUrl      https://aka.ms/aks-edge/k3s-msi

.EXAMPLE
    # Advanced: run against an already-existing cluster. Phase 2 detects
    # the existing cluster and short-circuits, so SP is not needed. Phase 3
    # uses the Arc machine's managed identity for the Arc operations.
    .\Install-AksEeBootstrap.ps1 `
        -ClusterName        aksee-cluster1 `
        -ResourceGroup      aksee-rg `
        -Subscription       00000000-0000-0000-0000-000000000000 `
        -Location           westus3 `
        -TenantId           00000000-0000-0000-0000-000000000000 `
        -CustomLocationsOid 00000000-0000-0000-0000-000000000000 `
        -AksEdgeMsiUrl      https://aka.ms/aks-edge/k3s-msi

.NOTES
Generated from `launcher-template.ps1` + `worker.ps1` +
`aksedge-config.template.json` by `Build-Launcher.ps1`. Regenerate after
editing any of those sources.
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory)] [string]$ClusterName,
    [Parameter(Mandatory)] [string]$ResourceGroup,
    [Parameter(Mandatory)] [string]$Subscription,
    [Parameter(Mandatory)] [string]$Location,
    [Parameter(Mandatory)] [string]$TenantId,
    [Parameter(Mandatory)] [string]$CustomLocationsOid,
    # SpAppId + SpPassword. AKS Edge Essentials requires SP credentials
    # to create the cluster in Phase 2, so both fields are part of the
    # standard happy path. Both can be omitted only when running against
    # an already-existing cluster (Phase 2 detects the cluster and skips
    # the create; Phase 3 falls through to the machine's managed identity).
    # The launcher enforces "both or neither" so the worker never sees a
    # half-populated config.
    [string]$SpAppId = '',
    [string]$SpPassword = '',
    [Parameter(Mandatory)] [string]$AksEdgeMsiUrl,
    [string]$ConfigDir         = 'C:\ProgramData\siteops\aksee-bootstrap',
    [string]$ScheduledTaskName = 'SiteOpsAksEeBootstrap',
    [string]$LocalAdminUser    = 'siteops-bootstrap',
    # Off by default to match the validated AIO baseline. Set 'true' when
    # downstream AIO needs workload-identity-backed secret sync. A string,
    # not a switch: the Arc Run Command delivers parameters as strings, and
    # a [bool]/[switch] would reject the 'false' the runCommand passes.
    [string]$EnableWorkloadIdentity = 'false',
    # Refuse to re-init when state.json shows an in-flight bootstrap.
    # Pass -Force to reset state to phase=0 and re-register the task
    # (destroys progress of any concurrent run).
    [switch]$Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$ConfirmPreference = 'None'
$ProgressPreference = 'SilentlyContinue'

# DPAPI LocalMachine encryption (Protect-StringMachine below) uses
# .NET Framework System.Security types that are only present under
# Windows PowerShell 5.1 ("Desktop" edition). PowerShell 7+ ("Core")
# has a different surface and would fail at Add-Type. Refuse to run
# under the wrong edition rather than producing a confusing
# Add-Type failure mid-encryption.
if ($PSVersionTable.PSEdition -ne 'Desktop') {
    throw "Install-AksEeBootstrap.ps1 requires Windows PowerShell 5.1 (Desktop). Detected: $($PSVersionTable.PSEdition) $($PSVersionTable.PSVersion). Re-run with 'powershell.exe -File Install-AksEeBootstrap.ps1 ...' instead of pwsh."
}

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

function Write-Log {
    param([string]$Message)
    $ts = (Get-Date).ToString('yyyy-MM-dd HH:mm:ss')
    Write-Host "[$ts] [launcher] $Message"
}

function Test-IsAdmin {
    $id = [System.Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object System.Security.Principal.WindowsPrincipal($id)
    return $principal.IsInRole([System.Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Protect-StringMachine {
    # Encrypts a string with DPAPI bound to the LocalMachine scope so any
    # admin on this host (including the Scheduled Task's local admin user)
    # can decrypt. Off-box exfiltration of the file cannot decrypt.
    param([string]$Plain)
    Add-Type -AssemblyName System.Security
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($Plain)
    $protected = [System.Security.Cryptography.ProtectedData]::Protect(
        $bytes,
        $null,
        [System.Security.Cryptography.DataProtectionScope]::LocalMachine)
    return [Convert]::ToBase64String($protected)
}

function New-RandomPassword {
    # Strong 24-char password (upper, lower, digit, symbol) for the local
    # admin user, drawn from a cryptographic RNG (GetBytes, for PS 5.1
    # compatibility) with rejection sampling to avoid modulo bias. The
    # credential grants local admin and can outlive the bootstrap on an
    # early failure, so it must be unpredictable.
    $upper = 'ABCDEFGHJKLMNPQRSTUVWXYZ'
    $lower = 'abcdefghijkmnpqrstuvwxyz'
    $digit = '23456789'
    $symbol = '!@#$%^&*()-_=+'
    $all = $upper + $lower + $digit + $symbol
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        # Uniform 0..max-1 for any alphabet under 256. Single-byte rejection
        # sampling: reject the top partial block so the result is unbiased.
        $idx = {
            param([int]$max)
            $b = New-Object 'byte[]' 1; $cap = 256 - (256 % $max)
            do { $rng.GetBytes($b) } while ($b[0] -ge $cap)
            $b[0] % $max
        }
        $chars = @($upper[(& $idx $upper.Length)], $lower[(& $idx $lower.Length)], $digit[(& $idx $digit.Length)], $symbol[(& $idx $symbol.Length)])
        for ($i = 0; $i -lt 20; $i++) { $chars += $all[(& $idx $all.Length)] }
        # Cryptographic Fisher-Yates shuffle so the required classes are not
        # pinned to the first positions.
        for ($i = $chars.Count - 1; $i -gt 0; $i--) { $j = & $idx ($i + 1); $t = $chars[$i]; $chars[$i] = $chars[$j]; $chars[$j] = $t }
        return -join $chars
    } finally {
        $rng.Dispose()
    }
}

function Set-StrictAcl {
    # Lock the config dir to Administrators + SYSTEM only. Removes the
    # inherited Users-read grant from ProgramData so non-admin local users
    # cannot read the (encrypted) SP secret blob.
    #
    # icacls is a native binary, so a non-zero exit does NOT raise under
    # $ErrorActionPreference='Stop'. Check $LASTEXITCODE explicitly after
    # each call. A silent /inheritance:r failure here would leave the
    # default ProgramData ACL in place (BUILTIN\Users: ReadAndExecute +
    # Write), and the subsequent /grant would only ADD entries without
    # stripping the inherited Users grant, breaking the secret-at-rest
    # guarantee the README describes.
    param([string]$Path)
    $inheritOut = & icacls $Path /inheritance:r 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "icacls /inheritance:r failed on ${Path} with exit ${LASTEXITCODE}: $inheritOut"
    }
    $grantOut = & icacls $Path /grant 'Administrators:(OI)(CI)F' 'SYSTEM:(OI)(CI)F' 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "icacls /grant failed on ${Path} with exit ${LASTEXITCODE}: $grantOut"
    }
    Write-Log "Locked ACLs on $Path to Administrators + SYSTEM"
}

function Set-LocalAdminUser {
    # Create or refresh the local admin user the Scheduled Task runs as.
    # Returns the plaintext password (needed for Register-ScheduledTask).
    param([string]$Username, [string]$Password)
    $secure = ConvertTo-SecureString $Password -AsPlainText -Force
    $user = Get-LocalUser -Name $Username -ErrorAction SilentlyContinue
    if ($null -eq $user) {
        Write-Log "Creating local user $Username"
        New-LocalUser -Name $Username -Password $secure -AccountNeverExpires -PasswordNeverExpires -UserMayNotChangePassword | Out-Null
    } else {
        Write-Log "Resetting password on existing local user $Username"
        Set-LocalUser -Name $Username -Password $secure
    }
    $group = Get-LocalGroupMember -Group 'Administrators' -Member $Username -ErrorAction SilentlyContinue
    if ($null -eq $group) {
        Write-Log "Adding $Username to local Administrators group"
        Add-LocalGroupMember -Group 'Administrators' -Member $Username
    }
}

# ---------------------------------------------------------------------------
# Embedded payloads
# ---------------------------------------------------------------------------

# === BEGIN EMBEDDED WORKER ===
$EmbeddedWorker = @'
<#
.SYNOPSIS
State-machine worker that bootstraps AKS Edge Essentials and Arc-connects
the cluster on a Windows VM. Resumes across reboots via a JSON state file.

.DESCRIPTION
Designed to run from a Scheduled Task that fires at startup and on demand.
The worker reads its current phase from `state.json` and cascades through
phases until either a reboot is pending or the bootstrap is complete.

  Phase 0  Pre-flight verification (admin, OS, memory, disk, nested virt).
  Phase 1  Install AKS Edge Essentials MSI, then Install-AksEdgeHostFeatures
           (may reboot when enabling Hyper-V).
  Phase 2  Render the AKS Edge Essentials config (Arc block values
           come from runtime parameters) and create the single-node
           K3s cluster. AKS Edge Essentials Arc-connects the cluster
           during this step.
  Phase 3  Layer AIO-specific Arc features on top of the cluster:
           install Azure CLI if missing, authenticate (managed
           identity by default, service principal as fallback), enable
           custom-locations and cluster-connect, and (when workload
           identity is requested) wire the OIDC issuer through the K3s
           apiserver.
  Phase 99 Cleanup (unregister scheduled task, remove bootstrap user,
           write final state).

Every phase is idempotent so re-runs from any state are safe. Phase 1 writes
the next phase to state.json BEFORE calling Install-AksEdgeHostFeatures so
the at-startup scheduled-task trigger resumes at Phase 2 after the reboot.

.PARAMETER ConfigDir
Directory holding `config.json`, `state.json`, `aksedge-config.template.json`,
and per-invocation log files. Defaults to
`C:\ProgramData\siteops\aksee-bootstrap`. Override for local testing without
the launcher.

.EXAMPLE
    .\worker.ps1
    Read state and cascade through phases until pending-reboot or done.

.EXAMPLE
    .\worker.ps1 -ConfigDir C:\test\bootstrap
    Local-test invocation against a hand-authored config dir.

.NOTES
For local testing without the launcher, hand-author config.json and
state.json in the config dir, and copy aksedge-config.template.json into
the same dir. See README.md.
#>

[CmdletBinding()]
param(
    [string]$ConfigDir = 'C:\ProgramData\siteops\aksee-bootstrap'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
# Suppress confirmation prompts from cmdlets that ignore -Force or default
# to ShouldProcess. A non-interactive scheduled-task context cannot answer
# prompts, so any prompt would hang the worker.
$ConfirmPreference = 'None'
$ProgressPreference = 'SilentlyContinue'

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

$script:StatePath    = Join-Path $ConfigDir 'state.json'
$script:ConfigPath   = Join-Path $ConfigDir 'config.json'
$script:TemplatePath = Join-Path $ConfigDir 'aksedge-config.template.json'

function Write-Log {
    param([string]$Message)
    $ts = (Get-Date).ToString('yyyy-MM-dd HH:mm:ss')
    Write-Host "[$ts] $Message"
}

function Get-State {
    if (-not (Test-Path $script:StatePath)) {
        throw "State file not found at $script:StatePath. The launcher writes the initial state file. For local testing, see README.md."
    }
    return Get-Content -Raw -Path $script:StatePath | ConvertFrom-Json
}

function Set-State {
    param(
        [Parameter(Mandatory)] [int]$Phase,
        [Parameter(Mandatory)] [ValidateSet('running', 'pending-reboot', 'succeeded', 'failed')] [string]$Status,
        [string]$ErrorText
    )
    $state = [pscustomobject]@{
        phase       = $Phase
        status      = $Status
        lastUpdated = (Get-Date).ToString('o')
        error       = $ErrorText
    }
    # Atomic write: serialize to a sibling .tmp file then Move-Item to the
    # final path. Set-Content is not atomic on Windows, so a concurrent
    # reader (operator inspecting state.json, launcher -Force re-init
    # while the worker is mid-iteration) can hit truncated JSON. Move
    # within the same volume is atomic on NTFS.
    $tmpPath = "$script:StatePath.tmp"
    $state | ConvertTo-Json | Set-Content -Path $tmpPath -Encoding UTF8
    Move-Item -Path $tmpPath -Destination $script:StatePath -Force
}

function Get-Config {
    if (-not (Test-Path $script:ConfigPath)) {
        throw "Config file not found at $script:ConfigPath. The launcher writes the config from caller-supplied parameters."
    }
    return Get-Content -Raw -Path $script:ConfigPath | ConvertFrom-Json
}

function Test-IsAdmin {
    $id = [System.Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object System.Security.Principal.WindowsPrincipal($id)
    return $principal.IsInRole([System.Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Test-AksEdgeModuleInstalled {
    return $null -ne (Get-Module -ListAvailable -Name AksEdge)
}

function Test-AksEdgeDeployed {
    # Cluster is up when the kubeconfig exists and kubectl can reach the
    # API server. Module-only check is unreliable across AKS EE versions
    # because cmdlet names for deployment-info vary. Try the per-user
    # kubeconfig first, then fall back to the shared copy Phase 2 writes
    # under the config dir (which Phase 99 preserves). The fallback lets a
    # -Force re-run detect an existing cluster even though Phase 99 removed
    # the bootstrap user and its profile kubeconfig.
    $kubeconfig = Join-Path $env:USERPROFILE '.kube\config'
    if (-not (Test-Path $kubeconfig)) {
        $sharedKubeconfig = Join-Path $ConfigDir 'kubeconfig'
        if (Test-Path $sharedKubeconfig) {
            $kubeconfig = $sharedKubeconfig
        } else {
            return $false
        }
    }
    if (-not (Get-Command kubectl -ErrorAction SilentlyContinue)) { return $false }
    try {
        $null = & kubectl --kubeconfig=$kubeconfig get nodes --request-timeout=5s 2>&1
        return $LASTEXITCODE -eq 0
    } catch {
        return $false
    }
}

function Resolve-SpPassword {
    # Returns the plaintext SP password from config. When the launcher
    # encrypts the password (production path), config.spPasswordEncrypted
    # is $true and config.spPassword is a base64 DPAPI blob bound to the
    # LocalMachine scope. For local testing without the launcher, plain
    # text in config.spPassword is also accepted.
    param($Config)
    $isEncrypted = ($Config.PSObject.Properties.Name -contains 'spPasswordEncrypted') -and $Config.spPasswordEncrypted
    if (-not $isEncrypted) {
        return $Config.spPassword
    }
    Add-Type -AssemblyName System.Security
    $protectedBytes = [Convert]::FromBase64String($Config.spPassword)
    $plainBytes = [System.Security.Cryptography.ProtectedData]::Unprotect(
        $protectedBytes,
        $null,
        [System.Security.Cryptography.DataProtectionScope]::LocalMachine)
    return [System.Text.Encoding]::UTF8.GetString($plainBytes)
}

function Install-AzCliIfMissing {
    # Phase 3 needs `az` for connectedk8s connect + enable-features. The
    # Arc-onboarding flow uses `azcmagent`, not `az`, so a freshly-Arc-
    # connected VM may not have `az` on PATH yet. Install the official
    # MSI silently if missing, then refresh PATH so the current process
    # can find `az` without restarting.
    if (Get-Command az -ErrorAction SilentlyContinue) {
        Write-Log 'az CLI already present, skipping install'
        return
    }
    $msiUrl  = 'https://aka.ms/installazurecliwindowsx64'
    $msiPath = Join-Path $ConfigDir 'azurecli-installer.msi'
    $log     = Join-Path $ConfigDir 'az-msiexec.log'
    Write-Log "az CLI not on PATH. Downloading MSI from $msiUrl"
    Invoke-WebRequest -Uri $msiUrl -OutFile $msiPath -UseBasicParsing
    Write-Log "Installing az CLI MSI via msiexec /quiet, log at $log"
    $proc = Start-Process msiexec.exe -Wait -PassThru -ArgumentList @(
        '/i', $msiPath, '/quiet', '/norestart', '/L*V', $log
    )
    if ($proc.ExitCode -ne 0) {
        throw "az CLI MSI install failed (exit $($proc.ExitCode)). See $log."
    }
    Remove-Item $msiPath -ErrorAction SilentlyContinue
    # Refresh PATH so the new `az` is visible to this process. Same
    # rationale as the AKS Edge module path refresh in Phase 1.
    $env:Path = ([Environment]::GetEnvironmentVariable('Path', 'Machine') +
                 [IO.Path]::PathSeparator +
                 [Environment]::GetEnvironmentVariable('Path', 'User'))
    if (-not (Get-Command az -ErrorAction SilentlyContinue)) {
        throw "az CLI install reported success but `az` is still not on PATH. Check $log."
    }
    Write-Log "az CLI installed: $((& az version --output tsv --query '\"azure-cli\"' 2>$null) -join ' ')"
}

function Write-BootstrapStateTag {
    # Idempotent tag write on this Arc machine resource. Phase 99 calls
    # with 'succeeded'. The per-phase catch calls with 'failed-phase-N'.
    # A siteops `type: wait` step polls this tag to gate downstream
    # pipeline steps on actual bootstrap completion.
    #
    # Safe to call before az CLI is installed or authenticated. Logs and
    # returns without throwing. A failed tag write does not fail the
    # bootstrap.
    #
    # Required permission on the Phase 3 identity (managed identity by
    # default, service principal as fallback):
    # `Microsoft.Resources/tags/write` on the Arc machine resource.
    # `Contributor` covers it transitively. The narrow
    # `Kubernetes Cluster - Azure Arc Onboarding` role does not.
    #
    # Assumes the Arc machine resource name equals `$env:COMPUTERNAME`
    # (the `azcmagent connect` default). If overridden during onboarding,
    # the tag write fails on lookup. The constructed ID is logged for
    # manual tagging.
    param(
        [Parameter(Mandatory)] $config,
        [Parameter(Mandatory)] [string]$Value
    )

    if (-not (Get-Command az -ErrorAction SilentlyContinue)) {
        Write-Log "Skipping bootstrap-state tag write: az CLI not installed."
        return
    }

    $sub  = $config.subscription
    $rg   = $config.resourceGroup
    $name = $env:COMPUTERNAME
    if (-not $sub -or -not $rg -or -not $name) {
        Write-Log "Skipping bootstrap-state tag write: missing subscription / resourceGroup / COMPUTERNAME."
        return
    }

    $arcId = "/subscriptions/$sub/resourceGroups/$rg/providers/Microsoft.HybridCompute/machines/$name"
    $tagOut = & az tag update --resource-id $arcId --operation merge --tags "siteops.bootstrap.state=$Value" --only-show-errors 2>&1
    if ($LASTEXITCODE -ne 0) {
        Write-Log "WARNING: tag write failed on $arcId (exit $LASTEXITCODE): $tagOut. See README Prerequisites for the required Microsoft.Resources/tags/write grant."
        return
    }
    Write-Log "Wrote tag siteops.bootstrap.state=$Value on $arcId"
}

function Test-ClusterArcConnected {
    param([string]$ClusterName, [string]$ResourceGroup)
    try {
        $json = & az connectedk8s show --name $ClusterName --resource-group $ResourceGroup --output json 2>$null
        if ($LASTEXITCODE -ne 0) { return $false }
        $cluster = $json | ConvertFrom-Json
        return $cluster.connectivityStatus -eq 'Connected'
    } catch {
        return $false
    }
}

function Wait-ArcClusterReady {
    # Poll the connectedk8s resource until connectivityStatus is Connected.
    # When -WaitForIssuerUrl is set, also require oidcIssuerProfile.issuerUrl,
    # arcAgentProfile.agentState=Succeeded, and workload identity enabled.
    # The issuer URL can appear before the agents finish rolling out, so
    # gating on all three keeps the apiserver patch from racing the rollout.
    param(
        [string]$ClusterName,
        [string]$ResourceGroup,
        [int]$RetrySeconds = 10,
        [int]$MaxRetries   = 60,
        [switch]$WaitForIssuerUrl
    )
    for ($i = 0; $i -lt $MaxRetries; $i++) {
        $json = & az connectedk8s show --name $ClusterName --resource-group $ResourceGroup --output json 2>$null
        if ($LASTEXITCODE -eq 0) {
            $cluster = $json | ConvertFrom-Json
            $obj = if ($cluster.PSObject.Properties.Name -contains 'properties') { $cluster.properties } else { $cluster }
            $connStatus = $obj.connectivityStatus
            # StrictMode throws on an absent property rather than returning
            # $null, so guard the leaf. The issuer URL and agentState are
            # commonly absent in the window between enabling the issuer and
            # Arc finishing provisioning, which is what -WaitForIssuerUrl
            # polls through.
            $issuerUrl = $null
            if ($obj.PSObject.Properties.Name -contains 'oidcIssuerProfile' -and $null -ne $obj.oidcIssuerProfile -and
                $obj.oidcIssuerProfile.PSObject.Properties.Name -contains 'issuerUrl') {
                $issuerUrl = $obj.oidcIssuerProfile.issuerUrl
            }
            $agentState = $null
            if ($obj.PSObject.Properties.Name -contains 'arcAgentProfile' -and $null -ne $obj.arcAgentProfile -and
                $obj.arcAgentProfile.PSObject.Properties.Name -contains 'agentState') {
                $agentState = $obj.arcAgentProfile.agentState
            }
            $wiEnabled = $false
            if ($obj.PSObject.Properties.Name -contains 'securityProfile' -and $null -ne $obj.securityProfile -and
                $obj.securityProfile.PSObject.Properties.Name -contains 'workloadIdentity' -and $null -ne $obj.securityProfile.workloadIdentity) {
                $wiEnabled = [bool]$obj.securityProfile.workloadIdentity.enabled
            }
            if ($WaitForIssuerUrl) {
                Write-Log "Arc cluster status: connectivity=$connStatus agentState=$agentState issuerUrl=$(if ($issuerUrl) { 'present' } else { '(none)' }) wiEnabled=$wiEnabled"
            } else {
                Write-Log "Arc cluster status: connectivity=$connStatus"
            }
            if ($connStatus -eq 'Connected') {
                if (-not $WaitForIssuerUrl) {
                    return
                }
                if ((-not [string]::IsNullOrEmpty($issuerUrl)) -and $agentState -eq 'Succeeded' -and $wiEnabled) {
                    return $issuerUrl
                }
            }
        }
        Start-Sleep -Seconds $RetrySeconds
    }
    throw "Cluster $ClusterName did not reach $(if ($WaitForIssuerUrl) { 'connected + OIDC-issuer-provisioned + workload-identity-enabled' } else { 'connected' }) status within $($MaxRetries * $RetrySeconds)s"
}

function Patch-K3sApiServer {
    # Mirrors Restart-ApiServer (K3s branch) in AksEdgeQuickStartForAio.ps1.
    # K3s reads its config from /var/.eflow/config/k3s/k3s-config.yml.
    # Patch the service-account-issuer line in place, then restart k3s
    # so it picks up the new issuer URL. Reads the file back and asserts
    # the new URL is present, so a silent sed no-op (line missing or
    # different format) fails loudly rather than producing a cluster
    # that looks healthy but lacks the issuer.
    param([string]$IssuerUrl)
    Import-Module AksEdge
    Write-Log "Patching K3s apiserver service-account-issuer to $IssuerUrl"
    Invoke-AksEdgeNodeCommand -command "sudo cat /var/.eflow/config/k3s/k3s-config.yml | tee /home/aksedge-user/k3s-config.yml | tee /home/aksedge-user/k3s-config.yml.working > /dev/null" | Out-Null
    Invoke-AksEdgeNodeCommand -command "sudo sed -i 's|service-account-issuer.*|service-account-issuer=$IssuerUrl|' /home/aksedge-user/k3s-config.yml" | Out-Null
    Invoke-AksEdgeNodeCommand -command "sudo cp /home/aksedge-user/k3s-config.yml /var/.eflow/config/k3s/k3s-config.yml" | Out-Null

    # Verification: grep the patched line out and check the URL is there.
    # Silent no-op is the failure class that motivated all of Phase 3, so
    # we surface it explicitly rather than letting Wait-K3sApiServerReady
    # report success on an unpatched apiserver.
    $verify = Invoke-AksEdgeNodeCommand -command 'sudo grep service-account-issuer /var/.eflow/config/k3s/k3s-config.yml'
    if ($verify -notmatch [regex]::Escape($IssuerUrl)) {
        throw "Patch-K3sApiServer verification failed. Expected `'service-account-issuer=$IssuerUrl`' in k3s-config.yml but observed: $verify"
    }
    Write-Log 'Verified service-account-issuer is patched in k3s-config.yml'

    Write-Log 'Restarting k3s.service to load the patched config'
    Invoke-AksEdgeNodeCommand -command 'sudo systemctl restart k3s.service' | Out-Null
}

function Wait-K3sApiServerReady {
    # Mirrors Wait-ApiServerReady in AksEdgeQuickStartForAio.ps1. After
    # a k3s restart the apiserver takes 5-30 seconds to come back. Poll
    # /readyz until "ok" or timeout. Per-call --request-timeout=2s caps
    # each iteration so the advertised total timeout matches wall clock;
    # default client timeout (~30s) would let 120 iterations stretch to
    # ~1 hour without this.
    param([int]$MaxRetries = 120)
    for ($i = 0; $i -lt $MaxRetries; $i++) {
        $ret = & kubectl get --raw='/readyz' --request-timeout=2s 2>$null
        if ($ret -eq 'ok') {
            Write-Log 'K3s apiserver ready'
            return
        }
        Start-Sleep -Seconds 1
    }
    throw 'K3s apiserver did not become ready within 120 seconds'
}

# ---------------------------------------------------------------------------
# Phase implementations
# ---------------------------------------------------------------------------

function Invoke-Phase0 {
    param($config)
    Write-Log 'Phase 0: pre-flight verification'

    if (-not (Test-IsAdmin)) {
        throw 'Worker must run as Administrator. Install-AksEdgeHostFeatures and New-AksEdgeDeployment both require it.'
    }

    $os = Get-CimInstance Win32_OperatingSystem
    Write-Log "OS: $($os.Caption) ($($os.Version))"

    # AKS Edge Essentials supports Windows 10 IoT Enterprise / Enterprise /
    # Pro, Windows 11 Pro / Enterprise / IoT Enterprise, and Windows
    # Server 2022 or 2025. Server 2019 is NOT supported. Fail fast on
    # anything else rather than letting the AKS EE installer hit a
    # confusing error.
    $caption = $os.Caption.ToLower()
    $supported = $false
    if ($caption -like '*server 2022*' -or $caption -like '*server 2025*') {
        $supported = $true
    } elseif ($caption -match 'windows 1[01]') {
        if ($caption -like '*pro*' -or $caption -like '*enterprise*' -or $caption -like '*iot*') {
            $supported = $true
        }
    }
    if (-not $supported) {
        throw "Unsupported OS for AKS Edge Essentials: $($os.Caption). Needs Windows 10/11 Pro/Enterprise/IoT or Windows Server 2022/2025."
    }

    $memGB = [math]::Round($os.TotalVisibleMemorySize / 1MB, 1)
    Write-Log "Total memory: $memGB GB"
    # Floor is 12 GB: the AKS EE Linux guest requests 10 GB
    # (aksedge-config.template.json MemoryInMB) plus ~2 GB headroom for
    # the Windows host. AIO recommends 16 GB on top of that.
    if ($memGB -lt 12) {
        throw "Host has $memGB GB memory. AKS EE Linux guest requests 10 GB and the Windows host needs ~2 GB headroom (12 GB minimum). AIO additionally recommends 16 GB total."
    }

    $sysDrive = $env:SystemDrive.TrimEnd(':')
    $drive = Get-PSDrive -Name $sysDrive
    $freeGB = [math]::Round($drive.Free / 1GB, 1)
    Write-Log "Free space on ${sysDrive}: $freeGB GB"
    if ($freeGB -lt 30) {
        throw "Only $freeGB GB free on $($env:SystemDrive). AKS EE VM + container images need at least 30 GB."
    }

    $cpu = Get-CimInstance Win32_Processor | Select-Object -First 1
    Write-Log "VirtualizationFirmwareEnabled: $($cpu.VirtualizationFirmwareEnabled)"
    if ($cpu.VirtualizationFirmwareEnabled -ne $true) {
        # Some hypervisors expose nested virt without setting this flag.
        # Log a warning and let Phase 1 surface a clearer error if the
        # capability really is absent.
        Write-Log 'WARNING: nested virtualization may not be available. Phase 1 will fail loudly if it is.'
    }

    # Bootstrap the NuGet PSPackageProvider. New-AksEdgeDeployment's
    # internal Arc-connect path calls Get-PackageProvider -Name NuGet
    # without bootstrapping, so fresh Windows installs hit a misleading
    # "Invalid Azure Arc parameters detected" error in Phase 2 when the
    # actual cause is the missing provider. Pre-installing here means
    # Phase 2 finds it ready when the cmdlet asks for it. Also trust
    # PSGallery so any module install the cmdlet triggers does not stop
    # on the "untrusted repository" prompt.
    Write-Log 'Bootstrapping NuGet PSPackageProvider for AKS EE Arc-connect path'
    try {
        $nuget = Get-PackageProvider -Name NuGet -ListAvailable -ErrorAction SilentlyContinue |
                 Sort-Object Version -Descending | Select-Object -First 1
        if (-not $nuget -or $nuget.Version -lt [version]'2.8.5.201') {
            Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force -Scope AllUsers -ErrorAction Stop | Out-Null
            Write-Log 'NuGet PSPackageProvider installed'
        } else {
            Write-Log "NuGet PSPackageProvider already present (version $($nuget.Version))"
        }
        Set-PSRepository -Name PSGallery -InstallationPolicy Trusted -ErrorAction SilentlyContinue
    } catch {
        throw "Failed to bootstrap NuGet PSPackageProvider: $_. New-AksEdgeDeployment Arc-connect path will fail in Phase 2 without it."
    }

    Set-State -Phase 1 -Status 'running'
    Write-Log 'Phase 0: complete'
}

function Invoke-Phase1 {
    param($config)
    Write-Log 'Phase 1: install AKS EE MSI and enable Hyper-V'

    if (Test-AksEdgeModuleInstalled) {
        Write-Log 'AKS Edge module already installed, skipping MSI install'
    } else {
        $msiPath = Join-Path $ConfigDir 'aksedge-installer.msi'
        Write-Log "Downloading MSI from $($config.aksEdgeMsiUrl)"
        Invoke-WebRequest -Uri $config.aksEdgeMsiUrl -OutFile $msiPath -UseBasicParsing

        # Validate the downloaded file BEFORE handing to msiexec. A wrong
        # aka.ms link redirects to a small HTML error page, which msiexec
        # then rejects with a cryptic exit 1620. Catch it here with a
        # clearer message. Two checks:
        #   1. Size > 50MB (real AKS EE MSI is ~876MB; an HTML error blob
        #      is typically < 1MB).
        #   2. CFB/CDF magic bytes D0 CF 11 E0 (the file format MSI uses).
        $fileInfo = Get-Item $msiPath
        if ($fileInfo.Length -lt 50MB) {
            throw "Downloaded MSI at $msiPath is only $($fileInfo.Length) bytes (expected > 50MB). The URL '$($config.aksEdgeMsiUrl)' likely returned an error page rather than the installer. Verify the URL serves application/octet-stream and a binary > 50MB."
        }
        $header = [byte[]]::new(8)
        $fs = [System.IO.File]::OpenRead($msiPath)
        try { $null = $fs.Read($header, 0, 8) } finally { $fs.Close() }
        if ($header[0] -ne 0xD0 -or $header[1] -ne 0xCF -or $header[2] -ne 0x11 -or $header[3] -ne 0xE0) {
            $magic = '{0:X2} {1:X2} {2:X2} {3:X2}' -f $header[0],$header[1],$header[2],$header[3]
            throw "Downloaded file at $msiPath is not a valid MSI (magic bytes '$magic', expected 'D0 CF 11 E0'). The URL '$($config.aksEdgeMsiUrl)' likely returned an error page rather than the installer."
        }

        $msiLog = Join-Path $ConfigDir 'msiexec.log'
        Write-Log "Installing MSI via msiexec /quiet /norestart, log at $msiLog"
        $proc = Start-Process msiexec.exe -Wait -PassThru -ArgumentList @(
            '/i', $msiPath, '/quiet', '/norestart', '/L*V', $msiLog
        )
        if ($proc.ExitCode -ne 0) {
            throw "msiexec exited with code $($proc.ExitCode). See $msiLog for the install log."
        }
        Remove-Item $msiPath -ErrorAction SilentlyContinue
        Write-Log 'MSI install complete'
    }

    # MSI install adds the AksEdge module to the *machine* scope
    # PSModulePath, but the running process inherited PATH/PSModulePath
    # at launch. Refresh from registry so Import-Module can find the
    # newly-installed module without a fresh PowerShell session.
    $env:PSModulePath = ([Environment]::GetEnvironmentVariable('PSModulePath', 'Machine') +
                         [IO.Path]::PathSeparator +
                         [Environment]::GetEnvironmentVariable('PSModulePath', 'User'))
    $env:Path = ([Environment]::GetEnvironmentVariable('Path', 'Machine') +
                 [IO.Path]::PathSeparator +
                 [Environment]::GetEnvironmentVariable('Path', 'User'))

    Import-Module AksEdge

    # Write the next phase BEFORE Install-AksEdgeHostFeatures so the
    # at-startup trigger resumes at Phase 2 after the (possibly inevitable)
    # reboot. If no reboot happens, the cascade in Main falls through to
    # Phase 2 immediately.
    Set-State -Phase 2 -Status 'pending-reboot'

    Write-Log 'Calling Install-AksEdgeHostFeatures -Force'
    $result = Install-AksEdgeHostFeatures -Force
    Write-Log "Install-AksEdgeHostFeatures returned: $result"

    # Treat $false from the cmdlet as a real failure (matches the
    # convention used by Azure/AKS-Edge wrapper callers). Coerce to a
    # single boolean since some module versions return pipeline output
    # with multiple values; take the last element.
    $lastResult = @($result) | Select-Object -Last 1
    if ($lastResult -is [bool] -and -not $lastResult) {
        throw "Install-AksEdgeHostFeatures returned `$false. See AksEdge event logs and recent entries under C:\ProgramData\AksEdge for the host-feature install failure."
    }

    # Detect pending reboot via two authoritative signals: the Hyper-V
    # feature install state and the Component Based Servicing key. We do
    # not rely on the cmdlet return value because its semantics vary
    # across module versions and the cmdlet's own behavior is ambiguous
    # about whether it auto-reboots.
    $hvFeature = Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V-All -ErrorAction SilentlyContinue
    $featureRestartNeeded = $false
    if ($hvFeature -and $null -ne $hvFeature.RestartNeeded) {
        $featureRestartNeeded = [bool]$hvFeature.RestartNeeded
    }
    $cbsPending = Test-Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\RebootPending'

    if ($featureRestartNeeded -or $cbsPending) {
        Write-Log "Reboot pending (Hyper-V RestartNeeded=$featureRestartNeeded, CBS RebootPending=$cbsPending). Restarting now."
        Restart-Computer -Force
        Start-Sleep -Seconds 60
        exit 0
    }

    # No reboot needed. Mark phase 2 ready so the cascade picks it up.
    Set-State -Phase 2 -Status 'running'
    Write-Log 'Phase 1: complete (no reboot needed)'
}

function Invoke-Phase2 {
    param($config)
    Write-Log 'Phase 2: deploy single-node K3s cluster'

    # Purge any leftover rendered config from a hard-killed prior run before
    # the early-return path below. It can carry the plaintext SP secret if a
    # forced reboot or task timeout skipped the finally block last time.
    $renderedPath = Join-Path $ConfigDir 'aksedge-config.json'
    Remove-Item -Path $renderedPath -Force -ErrorAction SilentlyContinue

    if (Test-AksEdgeDeployed) {
        Write-Log 'AKS EE deployment already present, skipping'
        Set-State -Phase 3 -Status 'running'
        return
    }

    if (-not (Test-Path $script:TemplatePath)) {
        throw "Template not found at $script:TemplatePath. The launcher copies this alongside worker.ps1. For local testing, see README.md."
    }

    Import-Module AksEdge

    # AKS Edge Essentials' New-AksEdgeDeployment hard-requires populated
    # service principal credentials in the Arc block to create the cluster.
    # There is no flag to skip its own Arc-connect. Managed identity in
    # Phase 3 cannot satisfy this Phase 2 requirement. Fail fast with a
    # precise message rather than letting the operator hit a cryptic
    # 10-minute cmdlet failure mid-deploy.
    $hasAppId    = ($config.PSObject.Properties.Name -contains 'spAppId')    -and $config.spAppId
    $hasPassword = ($config.PSObject.Properties.Name -contains 'spPassword') -and $config.spPassword
    if (-not ($hasAppId -and $hasPassword)) {
        throw "AKS Edge Essentials requires a service principal to create the cluster. Re-run the launcher with -SpAppId and -SpPassword."
    }

    try {
        # Populate the Arc block in the rendered config from runtime
        # parameters. AKS Edge Essentials rejects null or absent Arc
        # values at schema-validate time, so the template ships nulls
        # purely as placeholders.
        #
        # AKS Edge Essentials Arc-connects the cluster as part of cluster
        # creation. Phase 3 detects the already-connected cluster and
        # layers AIO-specific features on top (custom-locations always,
        # OIDC issuer when workload identity is enabled).
        Write-Log "Rendering AKS EE config from $script:TemplatePath"
        $cfg = Get-Content -Raw -Path $script:TemplatePath | ConvertFrom-Json
        $cfg.Arc.ClusterName       = $config.clusterName
        $cfg.Arc.Location          = $config.location
        $cfg.Arc.ResourceGroupName = $config.resourceGroup
        $cfg.Arc.SubscriptionId    = $config.subscription
        $cfg.Arc.TenantId          = $config.tenantId
        $cfg.Arc.ClientId          = $config.spAppId
        $cfg.Arc.ClientSecret      = Resolve-SpPassword -Config $config
        $cfg | ConvertTo-Json -Depth 6 | Set-Content -Path $renderedPath -Encoding UTF8
        # Drop the in-memory plaintext as soon as the file is written. The
        # rendered file on disk is protected by the $ConfigDir ACL
        # (Administrators + SYSTEM only) and removed in the finally block.
        $cfg.Arc.ClientSecret = $null
        $cfg = $null

        # Spawn New-AksEdgeDeployment in a fresh child PowerShell process.
        # In-place ErrorActionPreference relaxation does NOT work because the
        # AKS EE module's internal functions reset $ErrorActionPreference='Stop'
        # in their own scope. With strict EAP propagated into the cmdlet, the
        # cmdlet's many native-binary calls (wssdagent.exe, nodectl.exe) get
        # their normal diagnostic stderr converted into terminating errors,
        # killing VM creation with cryptic "Virtual machine creation failed!"
        # and "Could not find virtual machine, removal failed" messages.
        #
        # A child process started with default settings (no StrictMode, default
        # EAP=Continue) runs the cmdlet in the exact environment Microsoft tested
        # against, matching what an operator running it interactively from a
        # fresh admin pwsh would see.
        #
        # Use -EncodedCommand for the child invocation to avoid PowerShell
        # quoting hazards across the process boundary.
        Write-Log "Calling New-AksEdgeDeployment in child PowerShell (this typically takes 10-15 minutes)"
        $childScript = "Import-Module AksEdge; New-AksEdgeDeployment -JsonConfigFilePath '$renderedPath' -Confirm:`$false -Force; exit `$LASTEXITCODE"
        $bytes = [System.Text.Encoding]::Unicode.GetBytes($childScript)
        $encoded = [Convert]::ToBase64String($bytes)

        $psExe = Join-Path $env:SystemRoot 'System32\WindowsPowerShell\v1.0\powershell.exe'
        $childLog    = Join-Path $ConfigDir ("aksee-deploy-{0}.log" -f (Get-Date -Format 'yyyyMMdd-HHmmss'))
        $childErrLog = "$childLog.err"
        Write-Log "Child stdout: $childLog"
        Write-Log "Child stderr: $childErrLog"

        $proc = Start-Process -FilePath $psExe `
            -ArgumentList @('-NoProfile', '-ExecutionPolicy', 'Bypass', '-EncodedCommand', $encoded) `
            -Wait -PassThru -NoNewWindow `
            -RedirectStandardOutput $childLog -RedirectStandardError $childErrLog

        Write-Log "New-AksEdgeDeployment child exited with code $($proc.ExitCode)"
        if ($proc.ExitCode -ne 0) {
            $tailOut = ''
            $tailErr = ''
            if (Test-Path $childLog)    { $tailOut = (Get-Content $childLog    -Tail 30 -ErrorAction SilentlyContinue) -join "`n" }
            if (Test-Path $childErrLog) { $tailErr = (Get-Content $childErrLog -Tail 30 -ErrorAction SilentlyContinue) -join "`n" }
            throw "New-AksEdgeDeployment exited with code $($proc.ExitCode).`nstdout tail:`n$tailOut`nstderr tail:`n$tailErr`nFull logs at $childLog and $childErrLog."
        }

        $kubeconfig = Join-Path $env:USERPROFILE '.kube\config'
        if (-not (Test-Path $kubeconfig)) {
            throw "Kubeconfig not written at $kubeconfig after New-AksEdgeDeployment. The cluster did not come up."
        }

        # Copy the kubeconfig to the shared config dir so the operator can
        # use it from their own session without needing the bootstrap user's
        # profile. The config dir ACL restricts to Administrators + SYSTEM
        # so the bearer token stays protected.
        $sharedKubeconfig = Join-Path $ConfigDir 'kubeconfig'
        Copy-Item -Path $kubeconfig -Destination $sharedKubeconfig -Force
        Write-Log "Copied kubeconfig to $sharedKubeconfig for operator use"

        Set-State -Phase 3 -Status 'running'
        Write-Log 'Phase 2: complete (cluster up)'
    } finally {
        # Always remove the rendered config. It contains the plaintext SP
        # secret in the Arc block. Phase 99's belt-and-suspenders cleanup
        # catches anything we miss here, but a mid-Phase-2 failure must
        # not leave the secret on disk longer than necessary.
        if (Test-Path $renderedPath) {
            Write-Log "Removing rendered config at $renderedPath"
            Remove-Item -Path $renderedPath -Force -ErrorAction SilentlyContinue
        }
    }
}

function Invoke-Phase3 {
    param($config)
    Write-Log 'Phase 3: Arc-connect cluster and enable AIO prereqs'

    $cluster = $config.clusterName
    $rg      = $config.resourceGroup
    $sub     = $config.subscription
    $loc     = $config.location
    $tenant  = $config.tenantId
    $oid     = $config.customLocationsOid
    $appId   = $config.spAppId

    # Workload identity + OIDC issuer are only needed when downstream AIO
    # uses workload-identity-backed secret sync. Default false keeps the
    # riskiest path opt-in. Set enableWorkloadIdentity true in config.json
    # to enable it.
    $enableWi = ($config.PSObject.Properties.Name -contains 'enableWorkloadIdentity') -and $config.enableWorkloadIdentity
    Write-Log "Workload identity + OIDC issuer requested: $enableWi"

    Install-AzCliIfMissing

    # Pin the AKS EE kubectl so the connectedk8s extension and any
    # ambient `kubectl` call later in this phase resolve consistently.
    # Hoisted above the connect/skip branch so re-entry on an already-
    # connected cluster keeps the same kubectl path.
    $env:KUBECTL_CLIENT_PATH = "$env:ProgramFiles\AksEdge\kubectl\kubectl.exe"

    # Point all kubectl/az operations at the shared kubeconfig that
    # Phase 2 wrote (or the operator pre-populated for debugging). The
    # az connectedk8s enable-features command reads kubeconfig from
    # $env:KUBECONFIG > $env:USERPROFILE\.kube\config. Using the shared
    # path makes Phase 3 work regardless of which Windows user runs it
    # (the scheduled task user's profile may differ from the user that
    # populated the default location, especially after a Phase 99 cleanup
    # + re-init).
    $sharedKubeconfig = Join-Path $ConfigDir 'kubeconfig'
    if (Test-Path $sharedKubeconfig) {
        $env:KUBECONFIG = $sharedKubeconfig
        Write-Log "Using shared kubeconfig at $sharedKubeconfig"
    } else {
        Write-Log "Shared kubeconfig not found at $sharedKubeconfig. az/kubectl will fall back to `$env:USERPROFILE\.kube\config (typical when Phase 2 wrote it as the current user)."
    }

    Write-Log 'Adding az extension: connectedk8s'
    & az extension add --name connectedk8s --upgrade --only-show-errors | Out-Null

    # Authenticate. Picks SP when both spAppId and spPassword are present
    # (the standard happy path where SP was supplied for Phase 2's cluster
    # create and carries into Phase 3 for consistency). Falls back to the
    # Arc machine's system-assigned managed identity when both are absent
    # (the "bring your own cluster" path where Phase 2 short-circuited
    # because the cluster already existed). MI keeps no secret on disk,
    # avoids DPAPI plumbing, and sidesteps the special-character-in-
    # password parsing risk on the launcher's command line.
    #
    # The Arc machine identity needs `Kubernetes Cluster - Azure Arc
    # Onboarding` (or broader Contributor) on the resource group for
    # connect + enable-features. One-time RBAC step per Arc machine.
    $useMi = -not ($config.PSObject.Properties.Name -contains 'spAppId' -and $config.spAppId) `
             -or -not ($config.PSObject.Properties.Name -contains 'spPassword' -and $config.spPassword)
    if ($useMi) {
        Write-Log 'Authenticating with Arc machine managed identity (az login --identity)'
        $loginOut = & az login --identity --only-show-errors 2>&1
        if ($LASTEXITCODE -ne 0) {
            throw "az login --identity failed: $loginOut. Ensure the Arc machine identity has Contributor (or Kubernetes Cluster - Azure Arc Onboarding) on the resource group."
        }
    } else {
        Write-Log "Authenticating as service principal $appId"
        $spSecret = Resolve-SpPassword -Config $config
        $loginOut = & az login --service-principal --username $appId --password $spSecret --tenant $tenant --only-show-errors 2>&1
        if ($LASTEXITCODE -ne 0) {
            throw "az login --service-principal failed for ${appId}: $loginOut"
        }
    }
    # Check exit code so a sub-access failure throws here instead of
    # producing misleading ResourceNotFound errors from subsequent
    # connectedk8s commands fired against the wrong default context.
    $accountSetOut = & az account set --subscription $sub 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "az account set --subscription $sub failed: $accountSetOut. The authenticated principal (managed identity or service principal) likely lacks access to subscription $sub."
    }

    if (Test-ClusterArcConnected -ClusterName $cluster -ResourceGroup $rg) {
        Write-Log "Cluster $cluster is already Arc-connected, skipping connect"
    } else {
        # Tag set mirrors AksEdgeQuickStartForAio.ps1 New-ConnectedCluster.
        $aksEdgeVersion = (Get-Module -Name AksEdge).Version.ToString()
        $tags = @('SKU=AKSEdgeEssentials', "AKSEEVersion=$aksEdgeVersion", 'ManagedBy=siteops-bootstrap')

        # --distribution aks_edge_k3s tells Arc the cluster type. WLIF + OIDC
        # issuer are NOT enabled here. Phase 2 already plain-connected the
        # cluster, so this block is skipped on the standard path. WLIF
        # enablement is centralized in the `az connectedk8s update` below.
        $connectArgs = @(
            '-g', $rg,
            '-n', $cluster,
            '-l', $loc,
            '--subscription', $sub,
            '--tags'
        ) + $tags + @(
            '--disable-auto-upgrade',
            '--distribution', 'aks_edge_k3s',
            '--only-show-errors'
        )

        Write-Log "Running az connectedk8s connect $cluster (5-10 minutes)"
        $connectOut = & az connectedk8s connect @connectArgs 2>&1
        if ($LASTEXITCODE -ne 0) {
            throw "az connectedk8s connect failed for ${cluster}: $connectOut"
        }
    }

    if ($enableWi) {
        # Phase 2 plain-connected the cluster and the check above skips the
        # connect, so enable the issuer + WLIF on the existing connection.
        # --enable-workload-identity installs the in-cluster webhook, so it
        # needs the routable kubeconfig set above. Idempotent on repeat.
        Write-Log 'Enabling OIDC issuer + workload identity (az connectedk8s update)'
        $wiUpdateOut = & az connectedk8s update -g $rg -n $cluster --enable-oidc-issuer --enable-workload-identity --only-show-errors 2>&1
        if ($LASTEXITCODE -ne 0) {
            throw "az connectedk8s update --enable-oidc-issuer failed for ${cluster}: $wiUpdateOut"
        }

        # Wait for Arc to provision the workload-identity agent AND
        # populate oidcIssuerProfile.issuerUrl. Issuer URL is the actual
        # precondition for Patch-K3sApiServer, so wait on that signal
        # (plus agentState + wiEnabled) rather than the looser
        # connectivityStatus.
        Write-Log 'Waiting for Arc to provision the OIDC issuer URL'
        $issuerUrl = Wait-ArcClusterReady -ClusterName $cluster -ResourceGroup $rg -WaitForIssuerUrl
        Write-Log "OIDC issuer URL: $issuerUrl"

        Patch-K3sApiServer -IssuerUrl $issuerUrl
        Wait-K3sApiServerReady

        # Restart the Arc agents so they re-handshake with the patched
        # apiserver. Matches the official AKS EE quickstart. Non-fatal on
        # timeout: a partial rollout is logged, not thrown.
        Write-Log 'Restarting azure-arc deployments to pick up the new issuer'
        & kubectl -n azure-arc rollout restart deployment | Out-Null
        if ($LASTEXITCODE -ne 0) { Write-Log 'WARNING: rollout restart (azure-arc) returned non-zero.' }
        & kubectl -n azure-arc rollout status deployment --timeout=300s | Out-Null
        if ($LASTEXITCODE -ne 0) { Write-Log 'WARNING: rollout status (azure-arc) did not complete in 300s.' }
    } else {
        Write-Log 'Workload identity not requested. Verifying basic Arc connection only.'
        Wait-ArcClusterReady -ClusterName $cluster -ResourceGroup $rg
    }

    # Custom locations gates AIO extension-based component installs.
    # Always required regardless of WI.
    Write-Log "Enabling custom-locations feature (OID $oid)"
    $featuresOut = & az connectedk8s enable-features `
        --name $cluster `
        --resource-group $rg `
        --features cluster-connect custom-locations `
        --custom-locations-oid $oid `
        --only-show-errors 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "az connectedk8s enable-features failed for ${cluster}: $featuresOut"
    }

    Set-State -Phase 99 -Status 'running'
    Write-Log "Phase 3: complete (cluster Arc-connected, custom-locations enabled$(if ($enableWi) { ', OIDC issuer wired' }))"
}

function Invoke-Phase99 {
    param($config)
    Write-Log 'Phase 99: cleanup'

    $taskName = 'SiteOpsAksEeBootstrap'
    if ($config.PSObject.Properties.Name -contains 'scheduledTaskName') {
        $taskName = $config.scheduledTaskName
    }
    $task = Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue
    if ($null -ne $task) {
        Write-Log "Unregistering scheduled task $taskName"
        Unregister-ScheduledTask -TaskName $taskName -Confirm:$false
    } else {
        Write-Log "Scheduled task $taskName not found, nothing to unregister"
    }

    # Remove the bootstrap local admin AND the profile directory it
    # leaves behind. `Remove-LocalUser` only deletes the SAM entry. The
    # profile dir holds the kubeconfig with a long-lived cluster bearer
    # token. Capture the SID first so the profile-by-SID lookup works
    # after the account is gone. Also defensively remove the rendered
    # AKS EE config in case Phase 2's finally block was skipped.
    $bootstrapUser = 'siteops-bootstrap'
    if ($config.PSObject.Properties.Name -contains 'localAdminUser') {
        $bootstrapUser = $config.localAdminUser
    }
    $user = Get-LocalUser -Name $bootstrapUser -ErrorAction SilentlyContinue
    $bootstrapSid = $null
    if ($null -ne $user) {
        $bootstrapSid = $user.SID.Value
        Write-Log "Removing local user $bootstrapUser (SID $bootstrapSid)"
        Remove-LocalUser -Name $bootstrapUser
    } else {
        Write-Log "Local user $bootstrapUser not found, nothing to remove"
    }
    if ($bootstrapSid) {
        $profile = Get-CimInstance -ClassName Win32_UserProfile -Filter "SID='$bootstrapSid'" -ErrorAction SilentlyContinue
        if ($null -ne $profile) {
            try {
                Remove-CimInstance -InputObject $profile -ErrorAction Stop
                Write-Log "Removed user profile $($profile.LocalPath)"
            } catch {
                Write-Log "WARNING: failed to remove user profile $($profile.LocalPath): $_. The kubeconfig under .kube\config persists on disk. Remove manually if needed."
            }
        }
    }
    $renderedPath = Join-Path $ConfigDir 'aksedge-config.json'
    if (Test-Path $renderedPath) {
        Remove-Item -Path $renderedPath -Force -ErrorAction SilentlyContinue
        Write-Log 'Removed leftover rendered config'
    }

    # Zero out the encrypted SP password blob in config.json once the
    # workstream has succeeded. DPAPI-LocalMachine binds the blob to the
    # host so off-box exfiltration cannot decrypt, but leaving the
    # encrypted secret around after the bootstrap is done is unnecessary
    # attack surface. The bring-your-own-cluster path has spPassword=''
    # already and the conditional below is a no-op.
    if (Test-Path $script:ConfigPath) {
        $cfg = Get-Content -Raw -Path $script:ConfigPath | ConvertFrom-Json
        if (($cfg.PSObject.Properties.Name -contains 'spPassword') -and $cfg.spPassword) {
            $cfg.spPassword = ''
            if ($cfg.PSObject.Properties.Name -contains 'spPasswordEncrypted') {
                $cfg.spPasswordEncrypted = $false
            }
            $cfg | ConvertTo-Json | Set-Content -Path $script:ConfigPath -Encoding UTF8
            Write-Log 'Zeroed SP password blob in config.json'
        }
    }

    try {
        Write-BootstrapStateTag -config $config -Value 'succeeded'
    } catch {
        Write-Log "WARNING: tag write helper threw: $_. Non-fatal."
    }

    Set-State -Phase 99 -Status 'succeeded'
    Write-Log 'Phase 99: complete. Bootstrap succeeded.'
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

if (-not (Test-Path $ConfigDir)) {
    New-Item -ItemType Directory -Path $ConfigDir -Force | Out-Null
}

$logPath = Join-Path $ConfigDir "worker-$(Get-Date -Format 'yyyyMMdd-HHmmss').log"
Start-Transcript -Path $logPath -Append | Out-Null
try {
    Write-Log "Worker started. ConfigDir=$ConfigDir Log=$logPath"

    while ($true) {
        $state  = Get-State
        $config = Get-Config
        $startPhase = $state.phase
        Write-Log "Resuming at phase=$startPhase status=$($state.status)"

        try {
            switch ($state.phase) {
                0  { Invoke-Phase0  -config $config }
                1  { Invoke-Phase1  -config $config }
                2  { Invoke-Phase2  -config $config }
                3  { Invoke-Phase3  -config $config }
                99 { Invoke-Phase99 -config $config }
                default { throw "Unknown phase: $($state.phase)" }
            }
        } catch {
            Write-Log "ERROR in phase ${startPhase}: $_"
            Set-State -Phase $startPhase -Status 'failed' -ErrorText $_.ToString()
            try {
                Write-BootstrapStateTag -config $config -Value "failed-phase-$startPhase"
            } catch {
                Write-Log "WARNING: tag write helper threw on failure path: $_. Original phase error re-raised below."
            }
            throw
        }

        $newState = Get-State
        if ($newState.phase -eq 99 -and $newState.status -eq 'succeeded') {
            Write-Log 'Bootstrap complete.'
            break
        }
        if ($newState.status -eq 'pending-reboot') {
            Write-Log 'Pending reboot. Worker exits.'
            break
        }
        if ($newState.phase -eq $startPhase) {
            Write-Log "Phase $startPhase did not advance. Stopping cascade to avoid infinite loop."
            break
        }
    }
} finally {
    Stop-Transcript | Out-Null
}
'@
# === END EMBEDDED WORKER ===

# === BEGIN EMBEDDED TEMPLATE ===
$EmbeddedTemplate = @'
{
  "_comment": "AKS Edge Essentials single-node K3s cluster config. The bootstrap substitutes the Arc block (ClusterName, Location, ResourceGroupName, SubscriptionId, TenantId, ClientId, ClientSecret) from runtime parameters before deploying, so the nulls here are placeholders. Cluster sizing (CpuCount, MemoryInMB, DataSizeInGB, LogSizeInGB) is fixed in this file. Rebuild the launcher with Build-Launcher.ps1 after editing.",

  "SchemaVersion": "1.16",
  "Version": "1.0",
  "DeploymentType": "SingleMachineCluster",

  "Init": {
    "ServiceIPRangeSize": 10
  },

  "Arc": {
    "ClusterName": null,
    "Location": null,
    "ResourceGroupName": null,
    "SubscriptionId": null,
    "TenantId": null,
    "ClientId": null,
    "ClientSecret": null
  },

  "Network": {
    "NetworkPlugin": "flannel",
    "Ip4AddressPrefix": null,
    "InternetDisabled": false,
    "SkipDnsCheck": false,
    "Proxy": {
      "Http": null,
      "Https": null,
      "No": "localhost,127.0.0.0/8,192.168.0.0/16,172.17.0.0/16,10.42.0.0/16,10.43.0.0/16,10.96.0.0/12,10.244.0.0/16,.svc"
    }
  },

  "User": {
    "AcceptEula": true,
    "AcceptOptionalTelemetry": false
  },

  "Machines": [
    {
      "LinuxNode": {
        "CpuCount": 4,
        "MemoryInMB": 10240,
        "MemoryHugePages": {
          "Size": null,
          "Count": null
        },
        "DataSizeInGB": 40,
        "LogSizeInGB": 4,
        "TimeoutSeconds": 300,
        "TpmPassthrough": false
      }
    }
  ]
}
'@
# === END EMBEDDED TEMPLATE ===

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

if (-not (Test-IsAdmin)) {
    throw 'Install-AksEeBootstrap.ps1 must run as Administrator.'
}

Write-Log "Bootstrapping cluster $ClusterName in $ResourceGroup ($Location)"

# Preflight: fail fast on unreachable or wrong-content MSI URL so we do
# not register a task that will fail Phase 1. HEAD request avoids a full
# binary download. Validates three things:
#   1. Status 200
#   2. Content-Type is NOT text/* (a wrong aka.ms link returns an HTML
#      error page with Content-Type text/html, which would otherwise
#      sail through to msiexec exit 1620).
#   3. Content-Length is > 50MB (the real AKS EE MSI is ~876MB; an HTML
#      error blob is typically < 1MB).
try {
    Write-Log "Pre-checking AKS EE MSI URL $AksEdgeMsiUrl"
    $head = Invoke-WebRequest -Uri $AksEdgeMsiUrl -Method Head -UseBasicParsing -ErrorAction Stop
    if ($head.StatusCode -ne 200) {
        throw "Unexpected status $($head.StatusCode) from MSI URL preflight."
    }
    $ct = $head.Headers['Content-Type']
    if ($ct -match '^text/') {
        throw "MSI URL returned Content-Type '$ct' (expected application/octet-stream or application/x-msi). The URL likely redirects to an error page rather than the installer."
    }
    $cl = [int64]0
    $rawLen = $head.Headers['Content-Length']
    if ($rawLen) { [void][int64]::TryParse(($rawLen | Select-Object -First 1), [ref]$cl) }
    if ($cl -gt 0 -and $cl -lt 50MB) {
        throw "MSI URL returned Content-Length $cl bytes (expected > 50MB). The URL likely redirects to an error page rather than the installer."
    }
} catch {
    throw "AKS EE MSI URL preflight failed for ${AksEdgeMsiUrl}: $_"
}

if (-not (Test-Path $ConfigDir)) {
    New-Item -ItemType Directory -Path $ConfigDir -Force | Out-Null
    Write-Log "Created $ConfigDir"
}
Set-StrictAcl -Path $ConfigDir

$workerPath   = Join-Path $ConfigDir 'worker.ps1'
$templatePath = Join-Path $ConfigDir 'aksedge-config.template.json'
$configPath   = Join-Path $ConfigDir 'config.json'
$statePath    = Join-Path $ConfigDir 'state.json'

# Re-init guard. Inspect any existing state.json before resetting state and
# re-registering the task. A bootstrap that is in flight must not be clobbered,
# and one that already succeeded must not be re-run (re-running would reset to
# phase 0, and Phase 99 already removed the bootstrap user, so Phase 2 would
# collide with the existing cluster and flip the state tag to failed). -Force
# overrides both, destroying any prior state for a deliberate re-bootstrap.
if ((Test-Path $statePath) -and -not $Force) {
    $inFlight = $false
    $alreadyDone = $false
    $existingPhase = $null
    $existingStatus = $null
    try {
        $existing = Get-Content -Raw -Path $statePath | ConvertFrom-Json
        if ($existing.PSObject.Properties.Name -contains 'status') {
            $existingStatus = $existing.status
            if ($existing.status -in @('running', 'pending-reboot')) {
                $inFlight = $true
            } elseif ($existing.status -eq 'succeeded') {
                $alreadyDone = $true
            }
            if ($existing.PSObject.Properties.Name -contains 'phase') {
                $existingPhase = $existing.phase
            }
        }
    } catch {
        # Unparseable state.json: warn and continue, since re-init repairs it.
        Write-Log "WARNING: existing state.json could not be parsed. Re-initializing. ($_)"
    }
    if ($inFlight) {
        throw "Bootstrap already in flight (state.json shows phase=$existingPhase status=$existingStatus). Pass -Force to reset state and re-register the task, or wait for the existing run to complete."
    }
    if ($alreadyDone) {
        # Idempotent re-apply. The cluster is already bootstrapped and the
        # state tag already reads succeeded, so the composition wait step
        # passes without any work here. Leave state, the task, and the user
        # untouched. -Force re-bootstraps from scratch.
        Write-Log "Bootstrap already completed (state.json shows phase=$existingPhase status=succeeded). Nothing to do. Pass -Force to re-bootstrap from scratch."
        Write-Output 'ALREADY-BOOTSTRAPPED'
        return
    }
}

Set-Content -Path $workerPath   -Value $EmbeddedWorker   -Encoding UTF8
Set-Content -Path $templatePath -Value $EmbeddedTemplate -Encoding UTF8
Write-Log "Wrote $workerPath and $templatePath"

$adminPassword = New-RandomPassword
Set-LocalAdminUser -Username $LocalAdminUser -Password $adminPassword

$encryptedSpPassword = ''
$useMi = -not $SpAppId -and -not $SpPassword
if ((-not $useMi) -and (-not $SpAppId -or -not $SpPassword)) {
    throw "SpAppId and SpPassword must be provided together (SP auth) or both omitted (MI auth)."
}
if (-not $useMi) {
    $encryptedSpPassword = Protect-StringMachine -Plain $SpPassword
}

$config = [pscustomobject]@{
    clusterName            = $ClusterName
    resourceGroup          = $ResourceGroup
    subscription           = $Subscription
    location               = $Location
    tenantId               = $TenantId
    customLocationsOid     = $CustomLocationsOid
    spAppId                = $SpAppId
    spPassword             = $encryptedSpPassword
    spPasswordEncrypted    = (-not $useMi)
    aksEdgeMsiUrl          = $AksEdgeMsiUrl
    scheduledTaskName      = $ScheduledTaskName
    localAdminUser         = $LocalAdminUser
    enableWorkloadIdentity = ($EnableWorkloadIdentity -ieq 'true')
}
$config | ConvertTo-Json | Set-Content -Path $configPath -Encoding UTF8
$authNote = if ($useMi) { 'managed identity' } else { 'SP password encrypted via DPAPI LocalMachine' }
Write-Log "Wrote $configPath (auth=$authNote, WI=$($EnableWorkloadIdentity -ieq 'true'))"

$initialState = [pscustomobject]@{
    phase       = 0
    status      = 'running'
    lastUpdated = (Get-Date).ToString('o')
    error       = $null
}
$initialStateTmp = "$statePath.tmp"
$initialState | ConvertTo-Json | Set-Content -Path $initialStateTmp -Encoding UTF8
Move-Item -Path $initialStateTmp -Destination $statePath -Force
Write-Log "Wrote $statePath (phase=0)"

$action = New-ScheduledTaskAction `
    -Execute 'powershell.exe' `
    -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$workerPath`" -ConfigDir `"$ConfigDir`""

# at-startup trigger handles the Hyper-V reboot resume in Phase 1.
# once-trigger ~30s out kicks off the initial run without needing a reboot.
$startupTrigger = New-ScheduledTaskTrigger -AtStartup
$onceTrigger    = New-ScheduledTaskTrigger -Once -At ((Get-Date).AddSeconds(30))

$principal = New-ScheduledTaskPrincipal `
    -UserId "$env:COMPUTERNAME\$LocalAdminUser" `
    -LogonType Password `
    -RunLevel Highest

$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -ExecutionTimeLimit (New-TimeSpan -Hours 4) `
    -MultipleInstances IgnoreNew

# No auto-restart on failure. Non-transient errors (wrong subscription,
# missing RBAC, etc.) would otherwise retry 3 times at 5-min intervals,
# overwriting state.json.error each time and hiding repeated identical
# failures from operators. The worker's idempotency makes manual
# re-invocation via Start-ScheduledTask safe and explicit when an
# operator decides a retry is warranted.

$task = New-ScheduledTask `
    -Action $action `
    -Trigger @($startupTrigger, $onceTrigger) `
    -Principal $principal `
    -Settings $settings

Register-ScheduledTask `
    -TaskName $ScheduledTaskName `
    -InputObject $task `
    -User "$env:COMPUTERNAME\$LocalAdminUser" `
    -Password $adminPassword `
    -Force | Out-Null
Write-Log "Registered Scheduled Task $ScheduledTaskName"

Start-ScheduledTask -TaskName $ScheduledTaskName
Write-Log "Started $ScheduledTaskName"

Write-Output 'REGISTERED'

