FROM docker.io/library/ubuntu@sha256:008173c23f95b170204355c12626cb5a965d779a7e1283b09e9cffbb1bf33ca3

RUN apt-get update -qq && DEBIAN_FRONTEND=noninteractive \
    apt-get install -y --no-install-recommends python3 python3-venv

USER 65534:65534
ENV PYTHONDONTWRITEBYTECODE=1
